try:
    print(a)
except:
    print("Exception found")    
